{
    'name': 'HR Payroll (Custom)',
    'version': '19.0.1.0.0',
    'summary': 'Payroll module with weekly schedule and overtime (TZS)',
    'description': 'Payroll module implementing weekly pay, overtime, salary rules and structures',
    'category': 'Human Resources',
    'author': 'Your Company',
    'website': 'https://www.yourcompany.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr',
        'hr_contract',
        'hr_attendance',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/salary_rule_categories.xml',
        'data/work_entry_types.xml',
        'data/salary_rules.xml',
        'data/salary_structure.xml',
        'data/salary_rule_data.xml',
        'views/hr_payroll_views.xml',
        'views/payslip_views.xml',
    ],
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}
